Controllers/DashboardController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Authorization;

namespace ProtectionNet.Controllers
{
    [Authorize]
    public class DashboardController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Error()
        {
            return View();
        }
    }
}

Controllers/ProfileController.cs
using System;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Stormpath.SDK.Account;
using Stormpath.SDK.Client;

namespace ProtectionNET.Controllers
{
    // This API controller is protected and requires the user to be logged in.
    // For authorization policies, see the comments in Startup.
    [Authorize]
    public class ProfileController : Controller
    {
        private readonly IClient stormpathClient;
        private readonly IAccount stormpathAccount;

        public ProfileController(IClient stormpathClient, Lazy<IAccount> stormpathAccount)
        {
            // Stormpath request objects injected via DI
            this.stormpathClient = stormpathClient;
            this.stormpathAccount = stormpathAccount.Value;
        }

        // GET: /<controller>/
        public IActionResult Index()
        {
            return View();
        }
    }
}

Views/Dashboard/Index.cshtml
@{
    ViewData["Title"] = "Protection Dashboard";
}

@if (Context.User.Identity.IsAuthenticated)
{
    <h2>@ViewData["Title"]</h2>

    <ul class="nav nav-tabs">
        <li class="active"><a data-toggle="tab" href="#applications">Applications</a></li>
        <li><a data-toggle="tab" href="#policies">Policies</a></li>
        <li><a data-toggle="tab" href="#search">Search</a></li>
    </ul>
    <div class="tab-content">
        @Html.Partial("Partials/Dashboard/_ApplicationsTab")
        @Html.Partial("Partials/Dashboard/_PoliciesTab")
        @Html.Partial("Partials/Dashboard/_SearchTab")
    </div>
}

Views/Shared/Partials/Dashboard/_ApplicationsTab.cshtml
<script src="~/js/applicationsTable.js"></script> 

<div id="applications" class="tab-pane fade in active">
    <h3>Your protection applications</h3>

    <div class="table-responsive">
        <table id="applicationsTable" class="table" summary="Table of current outstanding Protection applications.">
        <caption class="sr-only">Current outstanding protection applications</caption>
            <thead>
                <tr>
                    <th id="appref">Reference</th>
                    <th id="client">Client(s)</th>
                    <th id="cover">Cover</th>
                    <th id="status">Status</th>
                    <th id="lastchange">Last change</th>
                    <th id="notes">Notes</th>
                    <th id="actions">Actions<th>
                </tr>
            </thead>
        </table>
    </div>
</div>

Views/Shared/Partials/Dashboard/_PoliciesTab.cshtml
<script src="~/js/policiesTable.js"></script> 

<div id="policies" class="tab-pane fade in">
    <h3>Your protection policies</h3>

    <div class="table-responsive">
        <table id="policiesTable" class="table" summary="Table of current outstanding Protection policies.">
        <caption class="sr-only">Current outstanding protection policies</caption>
            <thead>
                <tr>
                    <th id="appref">Reference</th>
                    <th id="client">Client(s)</th>
                    <th id="cover">Cover</th>
                    <th id="status">Status</th>
                    <th id="lastchange">Last change</th>
                    <th id="notes">Notes</th>
                    <th id="actions">Actions<th>
                </tr>
            </thead>
        </table>
    </div>
</div>

Views/Shared/Partials/Dashboard/_SearchTab.cshtml
<div id="search" class="tab-pane fade">
    <h2>Search for a case</h2>
    <p>Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam.</p>
</div>

Views/Shared/Partials/Layout/_masthead.cshtml
<div class="gutter-set">
    <a href="#main" class="skip hidden">Skip to Main Content</a>
    <a href="/accessiblity" class="skip hidden">Site accessibility statement</a>
</div>
<header class="gutter-set">  
    <a id="aegonLogo" asp-controller="Dashboard" asp-action="Index" target="_self" title="Back to homepage">
        <svg id="aegonLogoSVG" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 153 57">
            <polygon fill="#231F20" points="57.7,49.4 56.5,45.8 134.2,45.8 134.2,49.4 " />
            <polygon fill="#0071BB" points="14.8,55.8 50.5,43.8 47.2,34.4 36.3,34.4 34.8,38.7 29.2,38.7 38.5,10.3 44.6,10.3 41.7,1.8 1.3,15.3 "
            />
            <path fill="#231F20" d="M28.3,28.8" />
            <path fill="#231F20" d="M69,15.1H54.3v6.1h11.2v4.6H54.3v8.1h15.9v4.8H54.1L49,23.4V10.3h20.1v4.8H69z" />
            <path fill="#231F20" d="M134.1,10.3c0,0,11.1,17.7,11.4,18.2c0.3,0.5,0.7,1.3,0.7,1.3h0.1c0,0-0.3-0.5-0.3-1.2s0-18.3,0-18.3h5.3v28.5
    H146l-11.4-18.3c0,0-0.3-0.4-0.5-1H134c0.2,0.6,0.2,1,0.2,1v18.3h-5.3V10.3H134.1z" />
            <path fill="#231F20" d="M84,27.9v-4.8h11.7v15.5h-4.5c0,0,0-1.6,0-2s0.2-0.9,0.2-0.9h-0.1c0,0.1-0.3,0.6-0.5,0.7
    C89.2,38.2,85.7,39,84,39c-9.2,0-13.6-6.8-13.6-14.7s4.7-15,13.6-15c5.6,0,10.3,3.6,11.7,8.1c0,0-4.8,2.2-4.8,2.1
    c-0.8-2.5-3.4-5.3-6.9-5.3c-4.2,0-7.9,3.2-7.9,10.1s3.8,9.8,8,9.8c4.3,0,6.8-3.4,7-6.3L84,27.9z" />
            <path fill="#231F20" d="M125.7,24.4c0,7.3-4.5,14.9-13.4,14.9s-13.4-7.6-13.4-14.9c0.1-8.2,5-14.9,13.4-14.9
    C121,9.6,125.7,17.1,125.7,24.4z M104.4,24.3c0,5.1,2.4,10.1,8,10.1c5.2,0,7.8-5,7.8-10.1c0-5.4-2.9-10.1-7.8-10.1
    C106.8,14.3,104.4,18.9,104.4,24.3z" />
            <polygon fill="#0071BB" points="45.7,29.6 37.6,29.6 41.5,17 " />
        </svg>
        <h1>Aegon uk plc</h1><span class="hidden"> (Return to homepage)</span>
    </a>
    <a id="btnMenu" href="#headerNav" class="header-nav-toggle" role="button" aria-controls="headerNav" aria-expanded="true">
        <span>Menu</span><span class="sr-only">(Show/hide mobile navigation)</span>
    </a>

    @if (Context.User.Identity.IsAuthenticated)
    {
        <nav id="headerNav" class="header-nav" data-state="open">
            <div id="navUtils">
                <form id="logout_form" action="/logout" method="post">
                    <a id="utilSecureCta" onclick="document.getElementById('logout_form').submit();" style="cursor: pointer;">Sign Out</a>
                </form>
                <a id="utilSupport" asp-controller="Profile" asp-action="Index"><span>Profile</span></a>
            </div>
            <div id="navPrimary">
                <a href="#"><span>Dashboard</span></a>
                <a href="#"><span>Document Service</span></a>
                <a href="#"><span>Guides and News</span></a>
            </div>
        </nav>
    }
    else
    {
        <nav id="headerNav" class="header-nav" data-state="open">
            <div id="navUtils">
                <a id="utilSecureCta" href="/login">Log In</a>
            </div>
            <div id="navPrimary">
                <a href="#">Welcome to Aegon Protection Services</a>
            </div>
        </nav>
    }
    <script src="~/js/mastheadscript.js" asp-append-version="false"></script>
</header>

            
            

Views/Shared/Partials/Layout/_scripts.cshtml
<script src="~/lib/jquery/dist/jquery.js"></script>
<script type="text/javascript">
    var cb = function() {
        var l = document.createElement('link'); l.rel = 'stylesheet'; l.type = 'text/css';
        l.href = 'css/core.css';
        //TODO - fix location it is injected into
        var h = document.getElementsByTagName('head')[0]; h.parentNode.appendChild(l, h);
    };

    var raf = requestAnimationFrame || mozRequestAnimationFrame || webkitRequestAnimationFrame || msRequestAnimationFrame;

    if (raf) raf(cb);
    else window.addEventListener('load', cb);
</script>

<script src="~/lib/bootstrap/js/tab.js"></script>

<script src="~/js/site.js" asp-append-version="false"></script>
<script src="~/js/jquery.dataTables.min.js"></script>

Views/Shared/Partials/Layout/_sitefooter.cshtml
<hr />
<footer>
    <p>&copy; 2016 - Aegon</p>
</footer>

Views/Shared/Partials/Layout/_styles.cshtml
<link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css"  asp-append-version="false"/>

<link rel="stylesheet" href="~/lib/theme/css/core.css"  asp-append-version="false"/>
<link rel="stylesheet" href="~/lib/theme/css/style.css"  asp-append-version="false"/>
<link rel="stylesheet" href="~/fonts/webfont.css"  asp-append-version="false"/>
<link rel="stylesheet" href="~/fonts/24-Simple-Line-Icons-Pro/style.css"  asp-append-version="false"/>
<link rel="stylesheet" href="~/fonts/60-Simple-Line-Icons-Pro/style.css"  asp-append-version="false"/>

Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Mvc.Razor;

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Aegon</title>  
      
    @Html.Partial("Partials/Layout/_styles") 
    @Html.Partial("Partials/Layout/_scripts")
</head>
<body>
    <div id="siteWrapper">
        @Html.Partial("Partials/Layout/_masthead") 
        <main id="main" class="gutter-set">
            @RenderBody()
            @Html.Partial("Partials/Layout/_siteFooter")
        </main>
    </div>
    @RenderSection("scripts", required: false)

    <script>
        $(document).ready(function(){
            $('.dataTables_length').hide();
            $('.dataTables_filter').hide();
        });
    </script>
</body>
</html>